package memory

import (
	"time"

	"example.com/alfabeauty-b2b/internal/domain/product"
	"github.com/google/uuid"
)

// DemoProducts returns demo product catalog data
func DemoProducts() []product.Product {
	now := time.Now().UTC()

	return []product.Product{
		// Hair Color Products
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000001"),
			Slug:        "glowmaster-permanent-color",
			Name:        "GlowMaster Permanent Color Series",
			Description: "Professional permanent hair color with 100% grey coverage. Available in 60+ shades.",
			BrandID:     BrandGlowMaster,
			CategoryID:  CatHairColor,
			Benefits: []string{
				"100% grey coverage",
				"Long-lasting vibrant color",
				"Low ammonia formula",
				"Includes conditioning agents",
			},
			UseCases: []string{
				"Full head color application",
				"Root touch-up services",
				"Grey blending",
				"Fashion color transformation",
			},
			HowToUse:    "Mix 1:1.5 with GlowMaster Developer. Apply to dry hair. Process 35-45 minutes depending on desired lift.",
			Audience:    product.AudienceBoth,
			ImageURL:    "/images/products/glowmaster-permanent.jpg",
			GalleryURLs: []string{"/images/products/glowmaster-permanent-1.jpg", "/images/products/glowmaster-permanent-2.jpg"},
			TrainingURL: "/education/glowmaster-color-certification",
			IsActive:    true,
			SortOrder:   1,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000002"),
			Slug:        "glowmaster-bleach-powder",
			Name:        "GlowMaster Blue Bleach Powder",
			Description: "Dust-free professional bleaching powder with up to 9 levels of lift. Blue anti-yellow formula.",
			BrandID:     BrandGlowMaster,
			CategoryID:  CatHairColor,
			Benefits: []string{
				"Up to 9 levels of lift",
				"Dust-free formula",
				"Blue pigments neutralize yellow",
				"Contains protective oils",
			},
			UseCases: []string{
				"Balayage and highlights",
				"Full head lightening",
				"Color correction",
				"Creative coloring",
			},
			HowToUse:    "Mix 1:2 with developer (20-40 vol depending on desired lift). Monitor every 10 minutes. Maximum processing 50 minutes.",
			Audience:    product.AudienceSalon,
			ImageURL:    "/images/products/glowmaster-bleach.jpg",
			IsActive:    true,
			SortOrder:   2,
			CreatedAt:   now,
			UpdatedAt:   now,
		},

		// Hair Treatment Products
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000003"),
			Slug:        "salonlux-keratin-system",
			Name:        "SalonLux Keratin Treatment System",
			Description: "Professional keratin smoothing treatment for frizz control and hair repair. Results last 3-4 months.",
			BrandID:     BrandSalonLux,
			CategoryID:  CatHairTreatment,
			Benefits: []string{
				"Eliminates 95% of frizz",
				"Reduces styling time by 50%",
				"Repairs damaged hair structure",
				"Safe for colored hair",
			},
			UseCases: []string{
				"Frizz elimination treatment",
				"Hair smoothing service",
				"Damaged hair repair",
				"Brazilian blowout alternative",
			},
			HowToUse:    "Shampoo with clarifying shampoo 2x. Apply treatment section by section. Flat iron at 230°C. Complete post-care instructions provided.",
			Audience:    product.AudienceSalon,
			ImageURL:    "/images/products/salonlux-keratin.jpg",
			GalleryURLs: []string{"/images/products/salonlux-keratin-result.jpg"},
			TrainingURL: "/education/keratin-certification",
			IsActive:    true,
			SortOrder:   3,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000004"),
			Slug:        "salonlux-botox-treatment",
			Name:        "SalonLux Hair Botox Treatment",
			Description: "Deep conditioning treatment that fills gaps in hair fiber. No formaldehyde. Instant shine and softness.",
			BrandID:     BrandSalonLux,
			CategoryID:  CatHairTreatment,
			Benefits: []string{
				"Fills damaged hair fiber",
				"Instant shine and softness",
				"No formaldehyde",
				"Works on all hair types",
			},
			UseCases: []string{
				"Deep conditioning service",
				"Post-color treatment",
				"Damaged hair restoration",
				"Shine enhancement",
			},
			HowToUse:    "Apply to clean, damp hair. Leave for 20-30 minutes under heat cap. Rinse and style as desired.",
			Audience:    product.AudienceBoth,
			ImageURL:    "/images/products/salonlux-botox.jpg",
			IsActive:    true,
			SortOrder:   4,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000005"),
			Slug:        "alfapro-repair-mask",
			Name:        "AlfaPro Intensive Repair Mask",
			Description: "Professional-strength repair mask for severely damaged hair. Rebuilds hair from within.",
			BrandID:     BrandAlfaPro,
			CategoryID:  CatHairTreatment,
			Benefits: []string{
				"Rebuilds hair structure",
				"Intense hydration",
				"Reduces breakage by 80%",
				"Salon-exclusive formula",
			},
			UseCases: []string{
				"Post-bleaching treatment",
				"Weekly maintenance treatment",
				"Damaged hair repair program",
			},
			HowToUse:    "Apply generously to mid-lengths and ends. Leave 10-20 minutes. Rinse thoroughly.",
			Audience:    product.AudienceBoth,
			ImageURL:    "/images/products/alfapro-repair-mask.jpg",
			IsActive:    true,
			SortOrder:   5,
			CreatedAt:   now,
			UpdatedAt:   now,
		},

		// Styling Products
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000006"),
			Slug:        "barber-elite-classic-pomade",
			Name:        "BarberElite Classic Pomade",
			Description: "Water-based pomade with strong hold and high shine. Easy wash-out. Classic barbershop scent.",
			BrandID:     BrandBarberElite,
			CategoryID:  CatStyling,
			Benefits: []string{
				"Strong hold all day",
				"High shine finish",
				"Water-soluble (easy wash)",
				"Classic barbershop fragrance",
			},
			UseCases: []string{
				"Slick back styles",
				"Pompadour styling",
				"Side part looks",
				"Professional men's grooming",
			},
			HowToUse:    "Rub small amount between palms. Apply to damp or dry hair. Style as desired. Comb for defined look.",
			Audience:    product.AudienceBarber,
			ImageURL:    "/images/products/barber-elite-pomade.jpg",
			IsActive:    true,
			SortOrder:   6,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000007"),
			Slug:        "barber-elite-matte-clay",
			Name:        "BarberElite Matte Clay",
			Description: "Strong hold styling clay with natural matte finish. Perfect for textured, modern styles.",
			BrandID:     BrandBarberElite,
			CategoryID:  CatStyling,
			Benefits: []string{
				"Natural matte finish",
				"Strong, flexible hold",
				"Adds texture and volume",
				"Re-stylable throughout day",
			},
			UseCases: []string{
				"Textured crop styles",
				"Messy, natural looks",
				"Volume enhancement",
				"Modern men's cuts",
			},
			HowToUse:    "Work small amount between fingers. Apply to dry hair. Style with fingers for textured look.",
			Audience:    product.AudienceBarber,
			ImageURL:    "/images/products/barber-elite-clay.jpg",
			IsActive:    true,
			SortOrder:   7,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000008"),
			Slug:        "alfapro-heat-protector",
			Name:        "AlfaPro Thermal Shield Spray",
			Description: "Professional heat protection spray. Protects hair up to 230°C. Adds shine without weight.",
			BrandID:     BrandAlfaPro,
			CategoryID:  CatStyling,
			Benefits: []string{
				"Heat protection up to 230°C",
				"Prevents thermal damage",
				"Adds shine and smoothness",
				"Lightweight formula",
			},
			UseCases: []string{
				"Before blow-drying",
				"Before flat ironing",
				"Before curling",
				"Daily heat styling protection",
			},
			HowToUse:    "Spray evenly on damp hair from 15cm distance. Comb through. Proceed with heat styling.",
			Audience:    product.AudienceBoth,
			ImageURL:    "/images/products/alfapro-heat-spray.jpg",
			IsActive:    true,
			SortOrder:   8,
			CreatedAt:   now,
			UpdatedAt:   now,
		},

		// Tools & Equipment
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000009"),
			Slug:        "stylepro-ionic-dryer",
			Name:        "StylePro Ionic Professional Hair Dryer",
			Description: "2200W professional hair dryer with ionic technology. Reduces drying time by 40%. 2 concentrators included.",
			BrandID:     BrandStylePro,
			CategoryID:  CatTools,
			Benefits: []string{
				"2200W powerful motor",
				"Ionic technology for shine",
				"40% faster drying",
				"Ergonomic lightweight design",
			},
			UseCases: []string{
				"Professional blow-dry service",
				"High-volume salon use",
				"Smooth and bouncy finishes",
			},
			HowToUse:    "Use appropriate heat setting for hair type. Keep 15cm distance. Use concentrator for precision styling.",
			Audience:    product.AudienceBoth,
			ImageURL:    "/images/products/stylepro-dryer.jpg",
			IsActive:    true,
			SortOrder:   9,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000010"),
			Slug:        "stylepro-titanium-iron",
			Name:        "StylePro Titanium Flat Iron",
			Description: "Professional flat iron with titanium plates. Adjustable temperature 150-230°C. Floating plates for smooth glide.",
			BrandID:     BrandStylePro,
			CategoryID:  CatTools,
			Benefits: []string{
				"Titanium plates for durability",
				"Adjustable 150-230°C",
				"Floating plates technology",
				"Fast heat-up (30 seconds)",
			},
			UseCases: []string{
				"Straightening service",
				"Keratin sealing",
				"Smooth finish styling",
				"Curling and waves",
			},
			HowToUse:    "Select temperature based on hair type. Take thin sections. Glide slowly from root to end. Use heat protector.",
			Audience:    product.AudienceSalon,
			ImageURL:    "/images/products/stylepro-iron.jpg",
			IsActive:    true,
			SortOrder:   10,
			CreatedAt:   now,
			UpdatedAt:   now,
		},

		// Education Kits
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000011"),
			Slug:        "glowmaster-color-starter-kit",
			Name:        "GlowMaster Color Education Kit",
			Description: "Complete starter kit for color education. Includes 12 colors, developers, tools, and training manual.",
			BrandID:     BrandGlowMaster,
			CategoryID:  CatEducation,
			Benefits: []string{
				"Complete learning system",
				"12 popular shades included",
				"Professional training manual",
				"Certification eligible",
			},
			UseCases: []string{
				"New colorist training",
				"Salon team education",
				"Color technique practice",
			},
			HowToUse:    "Follow training manual step-by-step. Practice on mannequin heads. Complete certification exam after training.",
			Audience:    product.AudienceSalon,
			ImageURL:    "/images/products/glowmaster-edu-kit.jpg",
			TrainingURL: "/education/glowmaster-color-certification",
			IsActive:    true,
			SortOrder:   11,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.MustParse("10000001-0000-0000-0000-000000000012"),
			Slug:        "barber-classic-cuts-kit",
			Name:        "BarberElite Classic Cuts Education Kit",
			Description: "Barbering education kit with classic techniques. Includes tools, products, and step-by-step guide.",
			BrandID:     BrandBarberElite,
			CategoryID:  CatEducation,
			Benefits: []string{
				"Classic barbering techniques",
				"Essential tools included",
				"Step-by-step tutorials",
				"Certification program",
			},
			UseCases: []string{
				"Barber apprentice training",
				"Classic cut techniques",
				"Fade mastery training",
			},
			HowToUse:    "Follow the structured curriculum. Practice each technique 10+ times. Submit portfolio for certification.",
			Audience:    product.AudienceBarber,
			ImageURL:    "/images/products/barber-edu-kit.jpg",
			TrainingURL: "/education/barber-classic-certification",
			IsActive:    true,
			SortOrder:   12,
			CreatedAt:   now,
			UpdatedAt:   now,
		},
	}
}
